apiVersion: v1
kind: Secret
metadata:
  name: prometheus-custom
data:
  # `echo -n '{"items":[{"key":"testing/prometheus-rulefiles-custom"}]}' | base64`
  configmaps.json: 'eyJpdGVtcyI6W3sia2V5IjoidGVzdGluZy9wcm9tZXRoZXVzLXJ1bGVmaWxlcy1jdXN0b20ifV19' 
  # echo -n '{"rule_files":["/etc/prometheus/rules/rules-0/*.rules"]}' | base64
  prometheus.yaml: 'eyJydWxlX2ZpbGVzIjpbIi9ldGMvcHJvbWV0aGV1cy9ydWxlcy9ydWxlcy0wLyoucnVsZXMiXX0=' 